### ISSUE TITLE
Rationale Just your type 

### ISSUE THREAD

**Issue by JakeSimpsonn** [JakeSimpsonn/just-your-type#1]
1. Explain your chosen concept.
For my concept i took a famous quote "Everything you've ever wanted is on the other side of fear" by  George Addair. My design is to create a wall that is the word fear and have "everything you've ever wanted" on one side of the wall and "is on the other side of fear" on the other side.

2. Why did you choose these typefaces?
The two typefaces that i chose for my design are "Open Sans & PT Mono". I chose these two different typeface because one is more bold and the other is more light to create contrast between both fonts. 

3. Why did you choose this type scale?
The used a very large type scale for the word "fear" to stand out on the page as the main focal point. I also used a smaller type scale form the main text of the quote to make it the secondary focal point. 

4. Why did you choose these colours?
The colours i chose are a dark grey, darker red and white. I used the dark grey for the background, the darker red on for the background of the wall/fear and white for the text to make it stand out and pop of the page. 

5. How did you effectively use grids & modular CSS? 
I used grid with seven columns to design my concept. 

6. What challenges did you overcome?
During the time coding this design i over came a few of problem with grid and placements. Before i had a 3 column grid that had to much padding, i struggled to move the text closer. 

Overall i struggles with placements of the text the size of boxes, but the project want quite fun and enjoyable.

@muxlowc

**Comment by muxlowc** [comment]
@JakeSimpsonn can you please close this issue?
